const { formDataToJSON } = require("./commonUtil");

const formData1 = {
	id: "1",
	websiteId: "19",
	"locales[0][id]": "1",
	"locales[0][localeId]": "117712",
	"locales[0][title]": "title ua",
	"locales[0][description]": "desc ua",
	"locales[0][content]": "content ua",
	"locales[0][rating]": "5",
	"locales[0][views]": "123",
	"locales[0][addedDate]": "",
	"locales[0][editedDate]": "",
	"locales[0][status]": "1",
	"locales[0][metaTitle]": "metaTitle ua",
	"locales[0][metaDescription]": "metaDescription ua",
	"locales[0][metaKeyWords]": "metaKeyWords ua",
	"locales[0][metaRobots]": "metaRobots ua",
	"locales[1][id]": "2",
	"locales[1][localeId]": "118923",
	"locales[1][title]": "title ru",
	"locales[1][description]": "desc ru",
	"locales[1][content]": "content ru",
	"locales[1][rating]": "2",
	"locales[1][views]": "11",
	"locales[1][addedDate]": "",
	"locales[1][editedDate]": "",
	"locales[1][status]": "0",
	"locales[1][metaTitle]": "metaTitle ru",
	"locales[1][metaDescription]": "metaDescription ru",
	"locales[1][metaKeyWords]": "metaKeyWords ru",
	"locales[1][metaRobots]": "",
	"locales[2][id]": "",
	"locales[2][localeId]": "123232",
	"locales[2][title]": "",
	"locales[2][description]": "",
	"locales[2][content]": "",
	"locales[2][rating]": "",
	"locales[2][views]": "",
	"locales[2][addedDate]": "",
	"locales[2][editedDate]": "",
	"locales[2][status]": "",
	"locales[2][metaTitle]": "",
	"locales[2][metaDescription]": "",
	"locales[2][metaKeyWords]": "",
	"locales[2][metaRobots]": "",
	"locales[3][id]": "",
	"locales[3][localeId]": "175918",
	"locales[3][title]": "",
	"locales[3][description]": "",
	"locales[3][content]": "",
	"locales[3][rating]": "",
	"locales[3][views]": "",
	"locales[3][addedDate]": "",
	"locales[3][editedDate]": "",
	"locales[3][status]": "",
	"locales[3][metaTitle]": "",
	"locales[3][metaDescription]": "",
	"locales[3][metaKeyWords]": "",
	"locales[3][metaRobots]": ""
};

const res = {
	id: "1",
	locales: [
		{
			addedDate: "",
			content: "content ua",
			description: "desc ua",
			editedDate: "",
			id: "1",
			localeId: "117712",
			metaDescription: "metaDescription ua",
			metaKeyWords: "metaKeyWords ua",
			metaRobots: "metaRobots ua",
			metaTitle: "metaTitle ua",
			rating: "5",
			status: "1",
			title: "title ua",
			views: "123"
		},
		{
			addedDate: "",
			content: "content ru",
			description: "desc ru",
			editedDate: "",
			id: "2",
			localeId: "118923",
			metaDescription: "metaDescription ru",
			metaKeyWords: "metaKeyWords ru",
			metaRobots: "",
			metaTitle: "metaTitle ru",
			rating: "2",
			status: "0",
			title: "title ru",
			views: "11"
		},
		{
			addedDate: "",
			content: "",
			description: "",
			editedDate: "",
			id: "",
			localeId: "123232",
			metaDescription: "",
			metaKeyWords: "",
			metaRobots: "",
			metaTitle: "",
			rating: "",
			status: "",
			title: "",
			views: ""
		},
		{
			addedDate: "",
			content: "",
			description: "",
			editedDate: "",
			id: "",
			localeId: "175918",
			metaDescription: "",
			metaKeyWords: "",
			metaRobots: "",
			metaTitle: "",
			rating: "",
			status: "",
			title: "",
			views: ""
		}
	],
	websiteId: "19"
};

describe("commonUtil", () => {
	test("formDataToJSON correct 1", () => {
		const result = formDataToJSON(formData1);
		expect(result).toEqual(res);
	});
});
